title: "I-Chen Chou"

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-soopr-seo-tag
  - jekyll-markdown-output
  - jekyll-llms-output

markdown: kramdown
highlighter: rouge

navbar_entries:
  - title: Home
    url: /

  - title: Blog
    url: blog

  - title: Resume/CV
    url: cv

  - title: Social Media
    url: links
