title: "I-Chen Chou"

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-soopr-seo-tag
  - jekyll-markdown-output

markdown: kramdown
highlighter: rouge

navigation:
  - title: Home
    url: /

  - title: About
    url: /about/
